site_name: acvr
site_url: https://janclemenslab.org/acvr
repo_url: https://github.com/janclemenslab/acvr
theme:
  name: shadcn
  logo: assets/acvr.svg
  favicon: assets/acvr.svg
  show_stargazers: false
markdown_extensions:
  - codehilite
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
nav:
  - Home: index.md
  - Usage: usage.md
  - Indexing & Modes: indexing.md
  - Technical: technical.md
  - Benchmarking: benchmark.md
  - API: api.md
